#! /bin/sh

# Set defaults
INPUT_PATH=src/frontline.lua
TEMP_PATH=bundled.lua
COPY_TO_CLIPBOARD=false

# Parse flags
while getopts "ci:o:" opt; do
  case $opt in
    c) COPY_TO_CLIPBOARD=true ;;
    i) INPUT_PATH="$OPTARG" ;;
    o) TEMP_PATH="$OPTARG" ;;
    *) echo "Usage: $0 [-c] [-i input-file] [-o output-file]" && exit 1 ;;
  esac
done
shift $((OPTIND-1))

npx luabundler bundle -p "./src/?.lua" -o $TEMP_PATH $INPUT_PATH

if [ "$COPY_TO_CLIPBOARD" = true ]; then
  cat $TEMP_PATH | clip
fi
